--------------------------------------------------------
--  File created - Thursday-June-17-2021   
--------------------------------------------------------
DROP TABLE EQUIPMENT cascade constraints;
DROP TABLE MEMBER cascade constraints;
DROP TABLE USAGE cascade constraints;
--------------------------------------------------------
--  DDL for Table EQUIPMENT
--------------------------------------------------------

  CREATE TABLE EQUIPMENT 
   (	EQUIPMENT_ID NUMBER(*,0), 
	EQUIPMENT_NAME VARCHAR2(100 CHAR), 
	MANUFACTURER VARCHAR2(100 CHAR), 
	COST NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE MEMBER 
   (	MEMBER_ID NUMBER(*,0), 
	MEMBER_NAME VARCHAR2(100 CHAR), 
	AGE NUMBER(*,0), 
	CONTACT VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table USAGE
--------------------------------------------------------

  CREATE TABLE USAGE 
   (	MEMBER_ID NUMBER(*,0), 
	EQUIPMENT_ID NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE GYMMS ;
REM INSERTING into EQUIPMENT
SET DEFINE OFF;
Insert into EQUIPMENT (EQUIPMENT_ID,EQUIPMENT_NAME,MANUFACTURER,COST) values (1,'Lats PullDown','Appollo Sports',329999);
REM INSERTING into MEMBER
SET DEFINE OFF;
Insert into MEMBER (MEMBER_ID,MEMBER_NAME,AGE,CONTACT) values (1,'Shehroz Ahmad',20,'0323243434');
REM INSERTING into USAGE
SET DEFINE OFF;
Insert into USAGE (MEMBER_ID,EQUIPMENT_ID) values (1,1);
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX MEMBER_PK ON MEMBER (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index EQUIPMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX EQUIPMENT_PK ON EQUIPMENT (EQUIPMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index USES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX USES_PK ON USAGE (MEMBER_ID, EQUIPMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE GYMMS ;
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE EQUIPMENT ADD CONSTRAINT EQUIPMENT_PK PRIMARY KEY (EQUIPMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ENABLE;
 
  ALTER TABLE EQUIPMENT MODIFY (EQUIPMENT_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USAGE
--------------------------------------------------------

  ALTER TABLE USAGE MODIFY (MEMBER_ID NOT NULL ENABLE);
 
  ALTER TABLE USAGE MODIFY (EQUIPMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE USAGE ADD CONSTRAINT USES_PK PRIMARY KEY (MEMBER_ID, EQUIPMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ENABLE;
 
  ALTER TABLE MEMBER MODIFY (MEMBER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table USAGE
--------------------------------------------------------

  ALTER TABLE USAGE ADD CONSTRAINT USES_EQUIPMENT_FK FOREIGN KEY (EQUIPMENT_ID)
	  REFERENCES EQUIPMENT (EQUIPMENT_ID) ENABLE;
 
  ALTER TABLE USAGE ADD CONSTRAINT USES_MEMBER_FK FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
